# Modified by Plumb contributors on 2026-09-20: opt-in persistent postings dependency.
[package]
name = "plumb"
description = "Plumb: independent PostgreSQL text-search proof of concept"
version = "0.1.0"
authors = ["Plumb contributors"]
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["pg18"]
pg17 = ["pgrx/pg17", "pgrx-tests/pg17"]
pg18 = ["pgrx/pg18", "pgrx-tests/pg18"]
pg_test = []

[dependencies]
plumb-postings = { path = "../postings" }
pgrx = "=0.19.1"
rustc-hash.workspace = true
thiserror.workspace = true
tokenizer = { path = "../tokenizer" }
tinql = { path = "../tinql" }
boldi-vigna = { path = "../boldi-vigna" }

[dev-dependencies]
pgrx-tests = "=0.19.1"
